### ISSUE TITLE
Allow to memoize a callable object

### ISSUE THREAD

**Issue by dpsanders** [marius311/Memoization.jl#1]
I am trying to memoize a callable object, e.g.

```jl
struct MyObject
    f::Function
end

@memoize (x::MyObject)(n::Integer) = (x.f)(n)
```

But this doesn't seem to be implemented yet?

**Comment by marius311** [comment]
Agreed, this would be cool to have, I will play with it, shouldn't be too hard.

**Comment by marius311** [comment]
Also, this is probably obvious, but in your original case you can already memoize the inner function:

```julia
obj = MyObject(@memoize function foo(x) 
    println("Computed $x")
    x
end)

obj(3) # now memoized
```

**Comment by marius311** [comment]
This should work now on the latest version (0.1.2). 

```julia

using Memoization

struct MyObject
    f::Function
end

@memoize (x::MyObject)(n::Integer) = (x.f)(n)

f = MyObject(x->@show(x))

f(2)
f(2) # memoized

```

Different `MyObject` instances will all have their own individual memoization caches. Let me know if you run into any issues!
