### ISSUE TITLE
Allocations when using Memoization

### ISSUE THREAD

**Issue by StefanMathis** [marius311/Memoization.jl#19]
Hello,

I noticed that repeatedly calling a memoized function allocates a lot of memory. Is this unavoidable? Consider the following MWE:

```julia
using Memoization

function func_ctr(ctr, a)
    ctr[1] += 1
    return a + 1
end

@memoize function func_ctr_mem(ctr, a)
    return func_ctr(ctr,a)
end

function main()

    ctr = Int64[0]
    ctr_mem = Int64[0]
    allocs = Vector{Int64}(undef,10)
    allocs_mem = Vector{Int64}(undef,10)
    for i in 1:10
        allocs[i] = @allocated func_ctr(ctr, 1)
        allocs_mem[i] = @allocated func_ctr_mem(ctr_mem, 1)
    end
    return ctr, ctr_mem, allocs, allocs_mem
end

ctr, ctr_mem, allocs, allocs_mem = main()
```
Running this leads to `ctr[1] = 10`, `ctr_mem[1] = 1`, which means that the memoized function has been executed just once. However, a lot of allocations were done. Compare the vector `allocs`, which shows zero allocations for each pass, to the vector `allocs_mem`, which has 64 allocations for the first pass and 32 for all subsequent ones.

**Comment by marius311** [comment]
Good question. I'm not completely sure, my first guess was that if you look at the output of 

```julia
@code_warntype func_ctr_mem(Int64[0], 1)
````

you'll see one uninferred line:

```julia
│   %14 = (Memoization._get!)(%9, %10, %13)::Any
```

and I thought maybe this was causing the allocation. However, you can get rid of that by defining:

```julia
@memoize IdDict{Any,Int} function func_ctr_mem(ctr, a)
    return func_ctr(ctr,a)
end
```

and you still have the 32 bytes. Can you maybe try https://docs.julialang.org/en/v1/manual/profile/#Memory-allocation-analysis and see if you can spot exactly where its coming from? Memoize.jl has the identical behavior fwiw so my guess is its something related to `get!`? (but Im not sure)

**Comment by StefanMathis** [comment]
Looking at the allocations in `get!`, I found the following:
```julia
        - function get!(default::Callable, h::Dict{K,V}, key::K) where V where K
        0     index = ht_keyindex2!(h, key)
        - 
        0     index > 0 && return h.vals[index]
        - 
        0     age0 = h.age
        0     v = convert(V, default())
        0     if h.age != age0
        0         index = ht_keyindex2!(h, key)
        -     end
        0     if index > 0
        0         h.age += 1
        0         @inbounds h.keys[index] = key
        0         @inbounds h.vals[index] = v
        -     else
       16         @inbounds _setindex!(h, v, key, -index)
        -     end
        0     return v
        - end
```
So `get!` allocates memory here, but going through the code didn't really explain to me why, as `_setindex!` doesn't seem to be called. When accessing an `IdDict` manually, no allocations occur.

Even more puzzling is the behaviour of my example code when you exchange the `IdDict` for a normal `Dict`. In this case, the memoized function is called the first five times (!), allocating 32 bytes each time, then no further allocations happen. This doesn't change if the number of runs is increased from 10 to an arbitrary number. Any clue why this happens? This also happens when using Memoize.jl, therefore the issue doesn't seem to be routed in Memoization.jl.

**Comment by marius311** [comment]
I'm still a bit perplexed myself, but I think its related to the way you're passing in the `ctr`, e.g. this is all zeros as hoped/expected:

```julia
@memoize foo(a) = a + 1

function main()
    for i = 1:10
        println(@allocated foo(1))
    end
end
```

Conversely, here's a MWE for reproducing the allocation that doesn't depend on Memoization at all:

```julia
const cache = IdDict{Tuple{Vector{Int},Int},Int}()

# this is basically what @memoize expands to:
function func_ctr_mem(ctr, a)
    _getter() = a + 1
    get!(_getter, cache, (ctr, a))
end

function main()
    ctr = Int[0]
    for i = 1:10
        println(@allocated func_ctr_mem(ctr, 1))
    end
end
```

I don't understand why this produces an allocation, but perhaps whatever it is doesn't actually arise in your real-world application? I also feel like I've heard that `@allocated` sometimes isn't totally right, so maybe its that? Could be worth asking on Discourse with this latter MWE.

**Comment by StefanMathis** [comment]
First of all, thank you very much for your interest in this matter. Unfortunately, the issue arises in my real-world application, which is why I found it in the first place while doing some allocation-hunting ;-)

Thank you very much for the MWE. I really do think this is worth discussing on Discourse, since it also reproduces the puzzling behaviour of the normal `Dict` (e.g. not producing any allocations at all when replacing `IdDict` with `Dict`). If you don't mind, I'd like to use the MWE for a Discourse discussion.

**Comment by marius311** [comment]
Happy to help, I'm unreasonably obsessed with the performance of this package :) and this does seem like an issue. Go ahead and post using my MWE (linking back to this issue if you'd like) and we'll see if anyone has any ideas

**Comment by StefanMathis** [comment]
Further discussion here: https://discourse.julialang.org/t/unexpected-allocations-when-accessing-iddict/65996

**Comment by StefanMathis** [comment]
Since this issue is not related to Memoization.jl, I'm closing it.
