### ISSUE TITLE
`@memoize` cannot handle underscore variables

### ISSUE THREAD

**Issue by matthias314** [marius311/Memoization.jl#31]
Example:
```
julia> @memoize f(_::Val{N}) where N = N
ERROR: syntax: all-underscore identifiers are write-only and their values cannot be used in expressions around /usr/local/julia-depot/packages/Memoization/7WxyR/src/Memoization.jl:209
```
Of course one could omit the underscore. However, it would be great if the statement

> All function definition or function call forms with args and/or kwargs and/or type parameters work.

from the READE file were true.

**Comment by matthias314** [comment]
Great, thanks for the swift correction!

By the way, you can iterate over a `String`, so you could check that a (non-empty) `Symbol` `sym` is all-underscore simply by saying `all(==('_'), string(sym))`.

**Comment by marius311** [comment]
thanks, added (also tagged a new release)
