### ISSUE TITLE
Uniformize syntax

### ISSUE THREAD

**Issue by cstjean** [marius311/Memoization.jl#9]
> Ok, so syntax like
> 
> `@memoize DiskDict("foo.dat") foo(x) = ....` 
> 
> now works on master.

from #4 

👍  I feel like the `@memoize Dict f(x) = ...` syntax should be deprecated though, in favor of `Dict()`. It's more consistent, simpler code, and it would allow 

```julia
shared_memo = LRU()
@memoize shared_memo f(x) = ...
@memoize shared_memo g(x) = ...
```

**Comment by marius311** [comment]
Thanks for the suggestion, yea I agree its more consistent. I will think about doing in it a future version. Note for the moment you can still do stuff like:
```julia
shared_memo = LRU()
@memoize ()->shared_memo f(x) = ...
@memoize ()->shared_memo g(x) = ...
```
Actually should probably mention this example in the Readme, even I wasn't sure it was going to work until I tried it just now.

**Comment by marius311** [comment]
Both of these work now (in generaly any arbitrary function calls that create a cache work)
```julia
@memoize Dict f(x) =
@memoize Dict() f(x) =
```
